{{- if .Values.nodeLocalDNS.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: node-local-dns
  labels:
{{ include "tsuru-monitoring.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      k8s-app: node-local-dns
  podMetricsEndpoints:
    - port: metrics
      scheme: http
{{- end }}
