{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "buildkit.configName" . }}
  labels:
    {{- include "buildkit.labels" . | nindent 4 }}
data:
  buildkitd.toml: |-
    {{- .Values.config | nindent 4 }}
{{- end }}
